//빌드 스크립트 자체를 실행하기 전에 필요한 설정 (예제에있는)
buildscript {
    ext {
        queryDslVersion = "5.0.0"
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.14'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.zerock'
version = '0.0.1-SNAPSHOT'
description = 'driveu'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'


    // === 수동 의존성 추가 === //

    // layout:decorate 사용
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:3.1.0'
    // QueryDSL 사용 (동적쿼리)
    implementation "com.querydsl:querydsl-jpa:${queryDslVersion}:jakarta"
    annotationProcessor(
            "jakarta.persistence:jakarta.persistence-api",
            "jakarta.annotation:jakarta.annotation-api",
            "com.querydsl:querydsl-apt:${queryDslVersion}:jakarta"
    )
    // ModelMapper — Entity <-> DTO 자동 매핑
    implementation 'org.modelmapper:modelmapper:3.1.0'
    // Swagger (수업예제에있던거)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0'
    // Thumbnailator — 이미지 썸네일
    implementation 'net.coobird:thumbnailator:0.4.16'
}

tasks.named('test') {
    useJUnitPlatform()
}


sourceSets{
    main{
        java{
            srcDirs = ["$projectDir/src/main/java", "$projectDir/build/generated"]
        }
    }
}

